/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_EndCityFinder */

#ifndef _Included_com_example_EndCityFinder
#define _Included_com_example_EndCityFinder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_EndCityFinder
 * Method:    findEndCities
 * Signature: (JIII)[Lcom/example/EndCity;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_EndCityFinder_findEndCities
  (JNIEnv *, jobject, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
